#include <stdio.h>
#include <string.h>

#include "NovaGL.h"

static const struct {
    const char *name;
    void *proc;
} novagl_proctable[] = {
    // *gl
    {"glActiveTexture", (void *) glActiveTexture},
    {"glActiveTextureARB", (void *) glActiveTextureARB},
    {"glAlphaFunc", (void *) glAlphaFunc},
    {"glAlphaFuncx", (void *) glAlphaFuncx},
    {"glArrayElement", (void *) glArrayElement},
    {"glAttachShader", (void *) glAttachShader},
    {"glBegin", (void *) glBegin},
    {"glBindAttribLocation", (void *) glBindAttribLocation},
    {"glBindBuffer", (void *) glBindBuffer},
    {"glBindFramebuffer", (void *) glBindFramebuffer},
    {"glBindRenderbuffer", (void *) glBindRenderbuffer},
    {"glBindTexture", (void *) glBindTexture},
    {"glBindVertexArray", (void *) glBindVertexArray},
    {"glBlendColor", (void *) glBlendColor},
    {"glBlendEquation", (void *) glBlendEquation},
    {"glBlendEquationOES", (void *) glBlendEquationOES},
    {"glBlendEquationSeparate", (void *) glBlendEquationSeparate},
    {"glBlendEquationSeparateOES", (void *) glBlendEquationSeparateOES},
    {"glBlendFunc", (void *) glBlendFunc},
    {"glBlendFuncSeparate", (void *) glBlendFuncSeparate},
    {"glBlitFramebuffer", (void *) glBlitFramebuffer},
    {"glBufferData", (void *) glBufferData},
    {"glBufferSubData", (void *) glBufferSubData},
    {"glCallList", (void *) glCallList},
    {"glCallLists", (void *) glCallLists},
    {"glCheckFramebufferStatus", (void *) glCheckFramebufferStatus},
    {"glClear", (void *) glClear},
    {"glClearColor", (void *) glClearColor},
    {"glClearColorx", (void *) glClearColorx},
    {"glClearDepth", (void *) glClearDepth},
    {"glClearDepthf", (void *) glClearDepthf},
    {"glClearDepthx", (void *) glClearDepthx},
    {"glClearStencil", (void *) glClearStencil},
    {"glClientActiveTexture", (void *) glClientActiveTexture},
    {"glClientActiveTextureARB", (void *) glClientActiveTextureARB},
    {"glClipPlane", (void *) glClipPlane},
    {"glColor3b", (void *) glColor3b},
    {"glColor3bv", (void *) glColor3bv},
    {"glColor3d", (void *) glColor3d},
    {"glColor3dv", (void *) glColor3dv},
    {"glColor3f", (void *) glColor3f},
    {"glColor3fv", (void *) glColor3fv},
    {"glColor3i", (void *) glColor3i},
    {"glColor3iv", (void *) glColor3iv},
    {"glColor3s", (void *) glColor3s},
    {"glColor3sv", (void *) glColor3sv},
    {"glColor3ub", (void *) glColor3ub},
    {"glColor3ubv", (void *) glColor3ubv},
    {"glColor3ui", (void *) glColor3ui},
    {"glColor3uiv", (void *) glColor3uiv},
    {"glColor3us", (void *) glColor3us},
    {"glColor3usv", (void *) glColor3usv},
    {"glColor4b", (void *) glColor4b},
    {"glColor4bv", (void *) glColor4bv},
    {"glColor4d", (void *) glColor4d},
    {"glColor4dv", (void *) glColor4dv},
    {"glColor4f", (void *) glColor4f},
    {"glColor4fv", (void *) glColor4fv},
    {"glColor4i", (void *) glColor4i},
    {"glColor4iv", (void *) glColor4iv},
    {"glColor4s", (void *) glColor4s},
    {"glColor4sv", (void *) glColor4sv},
    {"glColor4ub", (void *) glColor4ub},
    {"glColor4ubv", (void *) glColor4ubv},
    {"glColor4ui", (void *) glColor4ui},
    {"glColor4uiv", (void *) glColor4uiv},
    {"glColor4us", (void *) glColor4us},
    {"glColor4usv", (void *) glColor4usv},
    {"glColor4x", (void *) glColor4x},
    {"glColorMask", (void *) glColorMask},
    {"glColorMaterial", (void *) glColorMaterial},
    {"glColorPointer", (void *) glColorPointer},
    {"glCompileShader", (void *) glCompileShader},
    {"glCompressedTexImage2D", (void *) glCompressedTexImage2D},
    {"glCompressedTexSubImage2D", (void *) glCompressedTexSubImage2D},
    {"glCopyTexImage2D", (void *) glCopyTexImage2D},
    {"glCopyTexSubImage2D", (void *) glCopyTexSubImage2D},
    {"glCreateProgram", (void *) glCreateProgram},
    {"glCreateShader", (void *) glCreateShader},
    {"glCullFace", (void *) glCullFace},
    {"glDebugMessageCallback", (void *) glDebugMessageCallback},
    {"glDebugMessageCallbackKHR", (void *) glDebugMessageCallbackKHR},
    {"glDeleteBuffers", (void *) glDeleteBuffers},
    {"glDeleteFramebuffers", (void *) glDeleteFramebuffers},
    {"glDeleteLists", (void *) glDeleteLists},
    {"glDeleteProgram", (void *) glDeleteProgram},
    {"glDeleteRenderbuffers", (void *) glDeleteRenderbuffers},
    {"glDeleteShader", (void *) glDeleteShader},
    {"glDeleteTextures", (void *) glDeleteTextures},
    {"glDeleteVertexArrays", (void *) glDeleteVertexArrays},
    {"glDepthFunc", (void *) glDepthFunc},
    {"glDepthMask", (void *) glDepthMask},
    {"glDepthRange", (void *) glDepthRange},
    {"glDepthRangef", (void *) glDepthRangef},
    {"glDepthRangex", (void *) glDepthRangex},
    {"glDisable", (void *) glDisable},
    {"glDisableClientState", (void *) glDisableClientState},
    {"glDisableVertexAttribArray", (void *) glDisableVertexAttribArray},
    {"glDrawArrays", (void *) glDrawArrays},
    {"glDrawBuffer", (void *) glDrawBuffer},
    {"glDrawElements", (void *) glDrawElements},
    {"glDrawElementsBaseVertex", (void *) glDrawElementsBaseVertex},
    {"glDrawRangeElements", (void *) glDrawRangeElements},
    {"glDrawRangeElementsBaseVertex", (void *) glDrawRangeElementsBaseVertex},
    {"glEnable", (void *) glEnable},
    {"glEnableClientState", (void *) glEnableClientState},
    {"glEnableVertexAttribArray", (void *) glEnableVertexAttribArray},
    {"glEnd", (void *) glEnd},
    {"glEndList", (void *) glEndList},
    {"glFinish", (void *) glFinish},
    {"glFlush", (void *) glFlush},
    {"glFogCoordPointer", (void *) glFogCoordPointer},
    {"glFogf", (void *) glFogf},
    {"glFogfv", (void *) glFogfv},
    {"glFogi", (void *) glFogi},
    {"glFogiv", (void *) glFogiv},
    {"glFogx", (void *) glFogx},
    {"glFogxv", (void *) glFogxv},
    {"glFramebufferRenderbuffer", (void *) glFramebufferRenderbuffer},
    {"glFramebufferTexture2D", (void *) glFramebufferTexture2D},
    {"glFrontFace", (void *) glFrontFace},
    {"glFrustum", (void *) glFrustum},
    {"glFrustumf", (void *) glFrustumf},
    {"glFrustumx", (void *) glFrustumx},
    {"glGenBuffers", (void *) glGenBuffers},
    {"glGenFramebuffers", (void *) glGenFramebuffers},
    {"glGenLists", (void *) glGenLists},
    {"glGenRenderbuffers", (void *) glGenRenderbuffers},
    {"glGenTextures", (void *) glGenTextures},
    {"glGenVertexArrays", (void *) glGenVertexArrays},
    {"glGenerateMipmap", (void *) glGenerateMipmap},
    {"glGetAttribLocation", (void *) glGetAttribLocation},
    {"glGetBufferParameteriv", (void *) glGetBufferParameteriv},
    {"glGetCompressedTexImage", (void *) glGetCompressedTexImage},
    {"glGetError", (void *) glGetError},
    {"glGetFloatv", (void *) glGetFloatv},
    {"glGetIntegerv", (void *) glGetIntegerv},
    {"glGetLightfv", (void *) glGetLightfv},
    {"glGetMaterialfv", (void *) glGetMaterialfv},
    {"glGetMaterialiv", (void *) glGetMaterialiv},
    {"glGetProgramInfoLog", (void *) glGetProgramInfoLog},
    {"glGetProgramiv", (void *) glGetProgramiv},
    {"glGetShaderInfoLog", (void *) glGetShaderInfoLog},
    {"glGetShaderiv", (void *) glGetShaderiv},
    {"glGetString", (void *) glGetString},
    {"glGetTexEnvfv", (void *) glGetTexEnvfv},
    {"glGetTexEnviv", (void *) glGetTexEnviv},
    {"glGetTexImage", (void *) glGetTexImage},
    {"glGetTexParameterfv", (void *) glGetTexParameterfv},
    {"glGetTexParameteriv", (void *) glGetTexParameteriv},
    {"glGetUniformBlockIndex", (void *) glGetUniformBlockIndex},
    {"glGetUniformLocation", (void *) glGetUniformLocation},
    {"glHint", (void *) glHint},
    {"glIsBuffer", (void *) glIsBuffer},
    {"glIsEnabled", (void *) glIsEnabled},
    {"glIsFramebuffer", (void *) glIsFramebuffer},
    {"glIsList", (void *) glIsList},
    {"glIsTexture", (void *) glIsTexture},
    {"glLightModelf", (void *) glLightModelf},
    {"glLightModelfv", (void *) glLightModelfv},
    {"glLightModeli", (void *) glLightModeli},
    {"glLightModeliv", (void *) glLightModeliv},
    {"glLightModelxv", (void *) glLightModelxv},
    {"glLightf", (void *) glLightf},
    {"glLightfv", (void *) glLightfv},
    {"glLighti", (void *) glLighti},
    {"glLightiv", (void *) glLightiv},
    {"glLightxv", (void *) glLightxv},
    {"glLineWidth", (void *) glLineWidth},
    {"glLineWidthx", (void *) glLineWidthx},
    {"glLinkProgram", (void *) glLinkProgram},
    {"glLoadIdentity", (void *) glLoadIdentity},
    {"glLoadMatrixd", (void *) glLoadMatrixd},
    {"glLoadMatrixf", (void *) glLoadMatrixf},
    {"glLoadMatrixx", (void *) glLoadMatrixx},
    {"glLogicOp", (void *) glLogicOp},
    {"glMapBuffer", (void *) glMapBuffer},
    {"glMapBufferRange", (void *) glMapBufferRange},
    {"glMaterialf", (void *) glMaterialf},
    {"glMaterialfv", (void *) glMaterialfv},
    {"glMateriali", (void *) glMateriali},
    {"glMaterialiv", (void *) glMaterialiv},
    {"glMaterialx", (void *) glMaterialx},
    {"glMaterialxv", (void *) glMaterialxv},
    {"glMatrixMode", (void *) glMatrixMode},
    {"glMultMatrixd", (void *) glMultMatrixd},
    {"glMultMatrixf", (void *) glMultMatrixf},
    {"glMultMatrixx", (void *) glMultMatrixx},
    {"glMultiDrawArrays", (void *) glMultiDrawArrays},
    {"glMultiTexCoord2f", (void *) glMultiTexCoord2f},
    {"glMultiTexCoord2fARB", (void *) glMultiTexCoord2fARB},
    {"glMultiTexCoord2fv", (void *) glMultiTexCoord2fv},
    {"glMultiTexCoord2i", (void *) glMultiTexCoord2i},
    {"glMultiTexCoord4f", (void *) glMultiTexCoord4f},
    {"glNewList", (void *) glNewList},
    {"glNormal3b", (void *) glNormal3b},
    {"glNormal3bv", (void *) glNormal3bv},
    {"glNormal3d", (void *) glNormal3d},
    {"glNormal3dv", (void *) glNormal3dv},
    {"glNormal3f", (void *) glNormal3f},
    {"glNormal3fv", (void *) glNormal3fv},
    {"glNormal3i", (void *) glNormal3i},
    {"glNormal3iv", (void *) glNormal3iv},
    {"glNormal3s", (void *) glNormal3s},
    {"glNormal3sv", (void *) glNormal3sv},
    {"glNormal3x", (void *) glNormal3x},
    {"glNormalPointer", (void *) glNormalPointer},
    {"glOrtho", (void *) glOrtho},
    {"glOrthof", (void *) glOrthof},
    {"glOrthox", (void *) glOrthox},
    {"glPixelStoref", (void *) glPixelStoref},
    {"glPixelStorei", (void *) glPixelStorei},
    {"glPolygonMode", (void *) glPolygonMode},
    {"glPolygonOffset", (void *) glPolygonOffset},
    {"glPolygonOffsetx", (void *) glPolygonOffsetx},
    {"glPopAttrib", (void *) glPopAttrib},
    {"glPopClientAttrib", (void *) glPopClientAttrib},
    {"glPopDebugGroup", (void *) glPopDebugGroup},
    {"glPopMatrix", (void *) glPopMatrix},
    {"glPushAttrib", (void *) glPushAttrib},
    {"glPushClientAttrib", (void *) glPushClientAttrib},
    {"glPushDebugGroup", (void *) glPushDebugGroup},
    {"glPushMatrix", (void *) glPushMatrix},
    {"glReadBuffer", (void *) glReadBuffer},
    {"glReadPixels", (void *) glReadPixels},
    {"glRectf", (void *) glRectf},
    {"glRecti", (void *) glRecti},
    {"glRenderbufferStorage", (void *) glRenderbufferStorage},
    {"glRotated", (void *) glRotated},
    {"glRotatef", (void *) glRotatef},
    {"glRotatex", (void *) glRotatex},
    {"glScaled", (void *) glScaled},
    {"glScalef", (void *) glScalef},
    {"glScalex", (void *) glScalex},
    {"glScissor", (void *) glScissor},
    {"glShadeModel", (void *) glShadeModel},
    {"glShaderSource", (void *) glShaderSource},
    {"glStencilFunc", (void *) glStencilFunc},
    {"glStencilFuncSeparate", (void *) glStencilFuncSeparate},
    {"glStencilMask", (void *) glStencilMask},
    {"glStencilMaskSeparate", (void *) glStencilMaskSeparate},
    {"glStencilOp", (void *) glStencilOp},
    {"glStencilOpSeparate", (void *) glStencilOpSeparate},
    {"glTexCoord1d", (void *) glTexCoord1d},
    {"glTexCoord1dv", (void *) glTexCoord1dv},
    {"glTexCoord1f", (void *) glTexCoord1f},
    {"glTexCoord1fv", (void *) glTexCoord1fv},
    {"glTexCoord1i", (void *) glTexCoord1i},
    {"glTexCoord1iv", (void *) glTexCoord1iv},
    {"glTexCoord1s", (void *) glTexCoord1s},
    {"glTexCoord1sv", (void *) glTexCoord1sv},
    {"glTexCoord2d", (void *) glTexCoord2d},
    {"glTexCoord2dv", (void *) glTexCoord2dv},
    {"glTexCoord2f", (void *) glTexCoord2f},
    {"glTexCoord2fv", (void *) glTexCoord2fv},
    {"glTexCoord2i", (void *) glTexCoord2i},
    {"glTexCoord2iv", (void *) glTexCoord2iv},
    {"glTexCoord2s", (void *) glTexCoord2s},
    {"glTexCoord2sv", (void *) glTexCoord2sv},
    {"glTexCoord3d", (void *) glTexCoord3d},
    {"glTexCoord3dv", (void *) glTexCoord3dv},
    {"glTexCoord3f", (void *) glTexCoord3f},
    {"glTexCoord3fv", (void *) glTexCoord3fv},
    {"glTexCoord3i", (void *) glTexCoord3i},
    {"glTexCoord3iv", (void *) glTexCoord3iv},
    {"glTexCoord3s", (void *) glTexCoord3s},
    {"glTexCoord3sv", (void *) glTexCoord3sv},
    {"glTexCoord4d", (void *) glTexCoord4d},
    {"glTexCoord4dv", (void *) glTexCoord4dv},
    {"glTexCoord4f", (void *) glTexCoord4f},
    {"glTexCoord4fv", (void *) glTexCoord4fv},
    {"glTexCoord4i", (void *) glTexCoord4i},
    {"glTexCoord4iv", (void *) glTexCoord4iv},
    {"glTexCoord4s", (void *) glTexCoord4s},
    {"glTexCoord4sv", (void *) glTexCoord4sv},
    {"glTexCoordPointer", (void *) glTexCoordPointer},
    {"glTexEnvf", (void *) glTexEnvf},
    {"glTexEnvfv", (void *) glTexEnvfv},
    {"glTexEnvi", (void *) glTexEnvi},
    {"glTexEnviv", (void *) glTexEnviv},
    {"glTexEnvx", (void *) glTexEnvx},
    {"glTexEnvxv", (void *) glTexEnvxv},
    {"glTexGend", (void *) glTexGend},
    {"glTexGendv", (void *) glTexGendv},
    {"glTexGenf", (void *) glTexGenf},
    {"glTexGenfv", (void *) glTexGenfv},
    {"glTexGeni", (void *) glTexGeni},
    {"glTexGeniv", (void *) glTexGeniv},
    {"glTexImage1D", (void *) glTexImage1D},
    {"glTexImage2D", (void *) glTexImage2D},
    {"glTexParameterf", (void *) glTexParameterf},
    {"glTexParameterfv", (void *) glTexParameterfv},
    {"glTexParameteri", (void *) glTexParameteri},
    {"glTexParameteriv", (void *) glTexParameteriv},
    {"glTexParameterx", (void *) glTexParameterx},
    {"glTexSubImage1D", (void *) glTexSubImage1D},
    {"glTexSubImage2D", (void *) glTexSubImage2D},
    {"glTranslated", (void *) glTranslated},
    {"glTranslatef", (void *) glTranslatef},
    {"glTranslatex", (void *) glTranslatex},
    {"glUniform1f", (void *) glUniform1f},
    {"glUniform1i", (void *) glUniform1i},
    {"glUniform2f", (void *) glUniform2f},
    {"glUniform3f", (void *) glUniform3f},
    {"glUniform3fv", (void *) glUniform3fv},
    {"glUniform4f", (void *) glUniform4f},
    {"glUniform4fv", (void *) glUniform4fv},
    {"glUniform4iv", (void *) glUniform4iv},
    {"glUniformBlockBinding", (void *) glUniformBlockBinding},
    {"glUniformMatrix4fv", (void *) glUniformMatrix4fv},
    {"glUnmapBuffer", (void *) glUnmapBuffer},
    {"glUseProgram", (void *) glUseProgram},
    {"glVertex2d", (void *) glVertex2d},
    {"glVertex2dv", (void *) glVertex2dv},
    {"glVertex2f", (void *) glVertex2f},
    {"glVertex2fv", (void *) glVertex2fv},
    {"glVertex2i", (void *) glVertex2i},
    {"glVertex2iv", (void *) glVertex2iv},
    {"glVertex2s", (void *) glVertex2s},
    {"glVertex2sv", (void *) glVertex2sv},
    {"glVertex3d", (void *) glVertex3d},
    {"glVertex3dv", (void *) glVertex3dv},
    {"glVertex3f", (void *) glVertex3f},
    {"glVertex3fv", (void *) glVertex3fv},
    {"glVertex3i", (void *) glVertex3i},
    {"glVertex3iv", (void *) glVertex3iv},
    {"glVertex3s", (void *) glVertex3s},
    {"glVertex3sv", (void *) glVertex3sv},
    {"glVertex4d", (void *) glVertex4d},
    {"glVertex4dv", (void *) glVertex4dv},
    {"glVertex4f", (void *) glVertex4f},
    {"glVertex4fv", (void *) glVertex4fv},
    {"glVertex4i", (void *) glVertex4i},
    {"glVertex4iv", (void *) glVertex4iv},
    {"glVertex4s", (void *) glVertex4s},
    {"glVertex4sv", (void *) glVertex4sv},
    {"glVertexAttribPointer", (void *) glVertexAttribPointer},
    {"glVertexPointer", (void *) glVertexPointer},
    {"glViewport", (void *) glViewport},
    {"gluBuild2DMipmaps", (void *) gluBuild2DMipmaps},
    {"gluLookAt", (void *) gluLookAt},
    {"gluPerspective", (void *) gluPerspective},
#ifdef EXPOSE_VGL_FUNCS
    // *vgl
    {"vglAddSemanticBinding", (void *) vglAddSemanticBinding},
    {"vglAddSemanticBindingHint", (void *) vglAddSemanticBindingHint},
    {"vglColorPointer", (void *) vglColorPointer},
    {"vglColorPointerMapped", (void *) vglColorPointerMapped},
    {"vglDrawObjects", (void *) vglDrawObjects},
    {"vglIndexPointer", (void *) vglIndexPointer},
    {"vglIndexPointerMapped", (void *) vglIndexPointerMapped},
    {"vglTexCoordPointer", (void *) vglTexCoordPointer},
    {"vglTexCoordPointerMapped", (void *) vglTexCoordPointerMapped},
    {"vglVertexPointer", (void *) vglVertexPointer},
    {"vglVertexPointerMapped", (void *) vglVertexPointerMapped},
    {"vglBindAttribLocation", (void *) vglBindAttribLocation},
    {"vglBindPackedAttribLocation", (void *) vglBindPackedAttribLocation},
    {"vglVertexAttribPointer", (void *) vglVertexAttribPointer},
    {"vglVertexAttribPointerMapped", (void *) vglVertexAttribPointerMapped},
    {"vglAlloc", (void *) vglAlloc},
    {"vglAllocFromScratch", (void *) vglAllocFromScratch},
    {"vglCalloc", (void *) vglCalloc},
    {"vglForceAlloc", (void *) vglForceAlloc},
    {"vglFree", (void *) vglFree},
    {"vglGetFuncName", (void *) vglGetFuncName},
    {"vglGetGxmTexture", (void *) vglGetGxmTexture},
    {"vglGetProcAddress", (void *) vglGetProcAddress},
    {"vglGetShaderBinary", (void *) vglGetShaderBinary},
    {"vglGetTexDataPointer", (void *) vglGetTexDataPointer},
    {"vglInit", (void *) vglInit},
    {"vglInitExtended", (void *) vglInitExtended},
    {"vglInitWithCustomSizes", (void *) vglInitWithCustomSizes},
    {"vglInitWithCustomThreshold", (void *) vglInitWithCustomThreshold},
    {"vglMalloc", (void *) vglMalloc},
    {"vglMallocUsableSize", (void *) vglMallocUsableSize},
    {"vglMemalign", (void *) vglMemalign},
    {"vglMemFree", (void *) vglMemFree},
    {"vglMemTotal", (void *) vglMemTotal},
    {"vglOverloadTexDataPointer", (void *) vglOverloadTexDataPointer},
    {"vglOverrideTexFormat", (void *) vglOverrideTexFormat},
    {"vglRealloc", (void *) vglRealloc},
    {"vglSetCircularPoolSize", (void *) vglSetCircularPoolSize},
    {"vglSetDisplayBufferCount", (void *) vglSetDisplayBufferCount},
    {"vglSetDisplayCallback", (void *) vglSetDisplayCallback},
    {"vglSetFragmentBufferSize", (void *) vglSetFragmentBufferSize},
    {"vglSetParamBufferSize", (void *) vglSetParamBufferSize},
    {"vglSetSemanticBindingMode", (void *) vglSetSemanticBindingMode},
    {"vglSetTextureCacheFrequency", (void *) vglSetTextureCacheFrequency},
    {"vglSetUSSEBufferSize", (void *) vglSetUSSEBufferSize},
    {"vglSetVDMBufferSize", (void *) vglSetVDMBufferSize},
    {"vglSetVertexAttribPoolSize", (void *) vglSetVertexAttribPoolSize},
    {"vglSetVertexBufferSize", (void *) vglSetVertexBufferSize},
    {"vglSetupDisplayRenderTarget", (void *) vglSetupDisplayRenderTarget},
    {"vglSetupGarbageCollector", (void *) vglSetupGarbageCollector},
    {"vglSetupScratchMemory", (void *) vglSetupScratchMemory},
    {"vglSetupShaderPatcher", (void *) vglSetupShaderPatcher},
    {"vglSetupRuntimeShaderCompiler", (void *) vglSetupRuntimeShaderCompiler},
    {"vglShaderGxpBinary", (void *) vglShaderGxpBinary},
    {"vglSwapBuffers", (void *) vglSwapBuffers},
    {"vglSwapResolution", (void *) vglSwapResolution},
    {"vglTexImageDepthBuffer", (void *) vglTexImageDepthBuffer},
    {"vglUseCachedMem", (void *) vglUseCachedMem},
    {"vglUseLowPrecision", (void *) vglUseLowPrecision},
    {"vglUseTripleBuffering", (void *) vglUseTripleBuffering},
    {"vglUseVram", (void *) vglUseVram},
    {"vglUseVramForUSSE", (void *) vglUseVramForUSSE},
    {"vglUseExtraMem", (void *) vglUseExtraMem},
    {"vglWaitVblankStart", (void *) vglWaitVblankStart},
#endif
    // *egl
    {"eglBindAPI", (void *) eglBindAPI},
    {"eglGetDisplay", (void *) eglGetDisplay},
    {"eglGetError", (void *) eglGetError},
    {"eglGetProcAddress", (void *) eglGetProcAddress},
    {"eglGetSystemTimeFrequencyNV", (void *) eglGetSystemTimeFrequencyNV},
    {"eglGetSystemTimeNV", (void *) eglGetSystemTimeNV},
    {"eglQueryAPI", (void *) eglQueryAPI},
    {"eglSwapInterval", (void *) eglSwapInterval},
    {"eglSwapBuffers", (void *) eglSwapBuffers},
};

static const size_t novagl_numproc = sizeof(novagl_proctable) / sizeof(*novagl_proctable);

void *novaglGetProcAddress(const char *name) {
    if (!name || !*name) {
        return NULL;
    }

    // Check only for actual OpenGL/VitaGL/EGL functions only
    if ((!(name[0] == 'g' && name[1] == 'l')) && (!(
            (name[0] == 'e' || name[0] == 'v') && name[1] == 'g' && name[2] == 'l'))) {
        return NULL;
    }

    // strip any extension markers
    const int len = strlen(name);
    char tmpname[len + 1];
    memcpy(tmpname, name, len + 1);
    /* Only strip a 3-char EXT/ARB/OES suffix when a real base name remains
     * (len > 3) — guards the `tmpname + len - 3` underflow for short names like
     * "gl" (len == 2). */
    if (len > 3 && (!strcmp(tmpname + len - 3, "EXT") || !strcmp(tmpname + len - 3, "ARB") ||
                    !strcmp(tmpname + len - 3, "OES"))) {
        tmpname[len - 3] = 0;
    }

    // search for stripped name
    for (size_t i = 0; i < novagl_numproc; ++i) {
        if (!strcmp(tmpname, novagl_proctable[i].name)) {
            return novagl_proctable[i].proc;
        }
    }

#ifdef FAKE_UNRESOLVED_FUNCS
    static int unresolved_id = 1;
#ifndef SKIP_ERROR_HANDLING
    vgl_log("%s:%d vglGetProcAddress: Requested an unimplemented function (%s). Returning 0x%08x\n", __FILE__, __LINE__,
            name, unresolved_id);
#endif
    return unresolved_id++;
#else
#ifndef SKIP_ERROR_HANDLING
    printf("%s:%d vglGetProcAddress: Requested an unimplemented function (%s).\n", __FILE__, __LINE__, name);
#endif
    return NULL;
#endif
}

char *novaglGetFuncName(uint32_t func) {
    // search for function name
    for (size_t i = 0; i < novagl_numproc; ++i) {
        if ((void *) func == novagl_proctable[i].proc)
            return (char *) novagl_proctable[i].name;
    }

#ifndef SKIP_ERROR_HANDLING
    printf("%s:%d vglGetFuncName: Requested an unimplemented function.\n", __FILE__, __LINE__);
#endif
    return NULL;
}
